version: "3.7"

services:
  node-red:
    build: node-red/.
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
      - ./output:/data/output

  mosquitto:
    image: eclipse-mosquitto:1.6.14
    ports:
      - 1883:1883
      #- 8083:8083
      #- 9001:9001
    volumes:
      - ./mosquitto/dev.conf:/mosquitto/config/mosquitto.conf
      #- ./iow/pablodecm/com:/etc/nginx/certs
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  nginx:
    build: nginx/.
    ports:
      - 80:80
      #- 443:443
    volumes:
      - ./dev-static:/usr/share/nginx/html
      #- ./iow.pablodecm.com:/etc/nginx/certs

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    ports:
      - 8000:8000
    volumes:
      - ./deployment/iow_data:/deployment/iow_data

volumes:
  node-red-data:
